import { defineEditorMessages } from "../messages";

const m = (fr: string, es: string, zhHans: string, ja: string, ko: string, ar: string) => ({
  fr, es, "zh-Hans": zhHans, ja, ko, ar
});

export const sharedMessages = defineEditorMessages("shared", {
  "Dialogue media": m("Média de dialogue", "Medios de diálogo", "对话媒体", "ダイアログメディア", "대화 미디어", "وسائط الحوار"),
  "Interaction media": m("Média d’interaction", "Medios de interacción", "交互媒体", "インタラクションメディア", "상호작용 미디어", "وسائط التفاعل"),
"15° snap": m("Snap à 15°", "chasquido de 15°", "15° 折断", "15°スナップ", "15° 스냅", "15 درجة المفاجئة"),
  "Assign an image or video to preview this scene.": m("Attribuez une image ou une vidéo pour prévisualiser cette scène.", "Asigne una imagen o un vídeo para obtener una vista previa de esta escena.", "指定图像或视频来预览该场景。", "このシーンをプレビューする画像またはビデオを割り当てます。", "이 장면을 미리 보려면 이미지나 비디오를 할당하세요.", "قم بتعيين صورة أو مقطع فيديو لمعاينة هذا المشهد."),
  "Close foreground media": m("Fermer les médias de premier plan", "Cerrar medios en primer plano", "关闭前台媒体", "フォアグラウンドメディアを閉じる", "전경 미디어 닫기", "إغلاق الوسائط الأمامية"),
  "Close {name}": m("Fermer {name}", "Cerrar {name}", "关闭 {name}", "{name} を閉じる", "{name} 닫기", "إغلاق {name}"),
  "Foreground media": m("Médias de premier plan", "Medios de primer plano", "前台媒体", "フォアグラウンドメディア", "전경 미디어", "الوسائط الأمامية"),
  "Hotspots: {count}": m("Points d'accès : {count}", "Puntos de acceso: {count}", "热点：{count}", "ホットスポット: {count}", "핫스팟: {count}", "النقاط الساخنة: {count}"),
  "Loading preview for {name}.": m("Chargement de l'aperçu pour {name}.", "Cargando vista previa para {name}.", "正在加载 {name} 的预览。", "{name} のプレビューを読み込んでいます。", "{name} 미리보기를 로드하는 중입니다.", "جارٍ تحميل المعاينة لـ {name}."),
  "Loading preview...": m("Chargement de l'aperçu...", "Cargando vista previa...", "正在加载预览...", "プレビューを読み込んでいます...", "미리보기 로드 중...", "جارٍ تحميل المعاينة..."),
  "No background asset": m("Aucun élément d'arrière-plan", "Sin activo en segundo plano", "无背景资产", "バックグラウンドアセットなし", "배경 자산 없음", "لا توجد أصول الخلفية"),
  "No playable {locale} variant.": m("Aucune variante jouable de {locale}.", "No hay variante jugable de {locale}.", "没有可玩的 {locale} 变体。", "プレイ可能な {locale} バリアントはありません。", "플레이 가능한 {locale} 변형이 없습니다.", "لا يوجد متغير {locale} قابل للتشغيل."),
  "No preview file is available for this asset.": m("Aucun fichier d'aperçu n'est disponible pour cet actif.", "No hay ningún archivo de vista previa disponible para este recurso.", "该资源没有可用的预览文件。", "このアセットに使用できるプレビュー ファイルはありません。", "이 자산에 사용할 수 있는 미리보기 파일이 없습니다.", "لا يتوفر ملف معاينة لهذا الأصل."),
  "No scene selected": m("Aucune scène sélectionnée", "Ninguna escena seleccionada", "未选择场景", "シーンが選択されていません", "선택한 장면이 없습니다.", "لم يتم تحديد أي مشهد"),
  "Non-visual asset selected": m("Élément non visuel sélectionné", "Activo no visual seleccionado", "选择非视觉资产", "非ビジュアル アセットが選択されました", "비시각적 자산이 선택됨", "تم تحديد الأصول غير المرئية"),
  "Pick another scene to preview it here.": m("Choisissez une autre scène pour la prévisualiser ici.", "Elija otra escena para obtener una vista previa aquí.", "选择另一个场景在此处预览。", "別のシーンを選択して、ここでプレビューします。", "여기에서 미리 보려면 다른 장면을 선택하세요.", "اختر مشهدًا آخر لمعاينته هنا."),
  "Preview the selected image asset directly inside the editor.": m("Prévisualisez l’image sélectionnée directement dans l’éditeur.", "Obtenga una vista previa del recurso de imagen seleccionado directamente dentro del editor.", "直接在编辑器内预览选定的图像资源。", "選択した画像アセットをエディタ内で直接プレビューします。", "편집기 내에서 직접 선택한 이미지 자산을 미리 봅니다.", "قم بمعاينة أصل الصورة المحددة مباشرة داخل المحرر."),
  "Preview the selected video asset directly inside the editor.": m("Prévisualisez la ressource vidéo sélectionnée directement dans l'éditeur.", "Obtenga una vista previa del recurso de video seleccionado directamente dentro del editor.", "直接在编辑器内预览选定的视频资源。", "選択したビデオ アセットをエディタ内で直接プレビューします。", "편집기 내에서 직접 선택한 비디오 자산을 미리 봅니다.", "قم بمعاينة أصل الفيديو المحدد مباشرة داخل المحرر."),
"Preview unavailable": m("Aperçu indisponible", "Vista previa no disponible", "预览不可用", "プレビューは利用できません", "미리보기를 사용할 수 없습니다.", "المعاينة غير متاحة"),
  "Preview unavailable because {reason} is assigned.": m("Aperçu indisponible car {reason} est attribué.", "La vista previa no está disponible porque se asignó {reason}.", "由于分配了 {reason}，预览不可用。", "{reason} が割り当てられているため、プレビューは利用できません。", "{reason}가 할당되어 미리보기를 사용할 수 없습니다.", "المعاينة غير متاحة لأنه تم تعيين {reason}."),
  "Preview unavailable for {name}.": m("Aperçu indisponible pour {name}.", "Vista previa no disponible para {name}.", "{name} 无法预览。", "{name} ではプレビューを利用できません。", "{name}에 대해서는 미리보기를 사용할 수 없습니다.", "المعاينة غير متاحة لـ {name}."),
  "Preview {name}.": m("Aperçu de {name}.", "Vista previa {name}.", "预览 {name}。", "{name} をプレビューします。", "{name}를 미리보세요.", "معاينة {name}."),
  "Scene preview. Click empty space to clear the hotspot selection, Ctrl+click empty space to add a hotspot, drag empty space to pan, use the mouse wheel to zoom, drag a hotspot to move it, or drag the orange handles to reshape it.": m("Aperçu de la scène. Cliquez sur un espace vide pour effacer la sélection du point chaud, sur un espace vide Ctrl+click pour ajouter un point chaud, faites glisser l'espace vide pour effectuer un panoramique, utilisez la molette de la souris pour zoomer, faites glisser un point chaud pour le déplacer ou faites glisser les poignées orange pour le remodeler.", "Vista previa de la escena. Haga clic en el espacio vacío para borrar la selección del punto de acceso, en el espacio vacío Ctrl+click para agregar un punto de acceso, arrastre el espacio vacío para realizar una panorámica, use la rueda del mouse para hacer zoom, arrastre un punto de acceso para moverlo o arrastre los controles naranjas para cambiarle la forma.", "场景预览。单击空白区域可清除热点选择，单击 Ctrl+click 空白区域可添加热点，拖动空白区域可平移，使用鼠标滚轮进行缩放，拖动热点可将其移动，或拖动橙色手柄可重塑其形状。", "シーンのプレビュー。ホットスポットの選択をクリアするには空のスペースをクリックし、ホットスポットを追加するには空のスペースをクリックし、パンするには空のスペースをドラッグし、ズームするにはマウスホイールを使用し、ホットスポットをドラッグして移動するか、オレンジ色のハンドルをドラッグして形状を変更します。", "장면 미리보기. 핫스팟 선택을 지우려면 빈 공간을 클릭하고, 핫스팟을 추가하려면 Ctrl+click 빈 공간을 클릭하고, 팬하려면 빈 공간을 드래그하고, 확대/축소하려면 마우스 휠을 사용하고, 핫스팟을 드래그하여 이동하거나, 주황색 핸들을 드래그하여 모양을 변경하세요.", "معاينة المشهد. انقر فوق مساحة فارغة لمسح تحديد نقطة الاتصال، أو Ctrl+click مساحة فارغة لإضافة نقطة اتصال، أو اسحب مساحة فارغة للتحريك، أو استخدم عجلة الماوس للتكبير/التصغير، أو اسحب نقطة فعالة لتحريكها، أو اسحب المقابض البرتقالية لإعادة تشكيلها."),
  "Scene preview. Click to zoom in, Shift-click to zoom out, or use the mouse wheel to zoom.": m("Aperçu de la scène. Cliquez pour zoomer, Shift-click pour effectuer un zoom arrière ou utilisez la molette de la souris pour zoomer.", "Vista previa de la escena. Haga clic para acercar, Shift-click para alejar o use la rueda del mouse para acercar.", "场景预览。单击放大，Shift-click 缩小，或使用鼠标滚轮缩放。", "シーンのプレビュー。クリックして拡大するか、Shift-click をクリックして縮小するか、マウス ホイールを使用して拡大します。", "장면 미리보기. 확대하려면 클릭하고, 축소하려면 Shift-click를, 확대하려면 마우스 휠을 사용하세요.", "معاينة المشهد. انقر للتكبير، أو Shift-click للتصغير، أو استخدم عجلة الماوس للتكبير."),
  "Scene preview. Ctrl+click anywhere on the media to add a hotspot at that normalized position. Drag empty space to pan and use the mouse wheel to zoom.": m("Aperçu de la scène. Ctrl+click n’importe où sur le support pour ajouter un point chaud à cette position normalisée. Faites glisser l'espace vide pour effectuer un panoramique et utilisez la molette de la souris pour zoomer.", "Vista previa de la escena. Ctrl+click en cualquier lugar del medio para agregar un punto de acceso en esa posición normalizada. Arrastre el espacio vacío para desplazarse y use la rueda del mouse para hacer zoom.", "场景预览。 Ctrl+click 媒体上的任何位置，以在该标准化位置添加热点。拖动空白区域进行平移并使用鼠标滚轮进行缩放。", "シーンのプレビュー。メディア上の任意の場所に Ctrl+click を入力すると、その正規化された位置にホットスポットが追加されます。空のスペースをドラッグしてパンし、マウス ホイールを使用してズームします。", "장면 미리보기. Ctrl+click는 미디어의 어느 위치에나 정규화된 위치에 핫스팟을 추가합니다. 빈 공간을 드래그하여 이동하고 마우스 휠을 사용하여 확대/축소합니다.", "معاينة المشهد. Ctrl+click في أي مكان على الوسائط لإضافة نقطة اتصال في هذا الموضع الطبيعي. اسحب المساحة الفارغة للتحريك واستخدم عجلة الماوس للتكبير/التصغير."),
  "Scene preview. Drag to pan the zoomed view, or use the mouse wheel to zoom.": m("Aperçu de la scène. Faites glisser pour effectuer un panoramique sur la vue agrandie ou utilisez la molette de la souris pour zoomer.", "Vista previa de la escena. Arrastra para desplazarte por la vista ampliada o utiliza la rueda del ratón para hacer zoom.", "场景预览。拖动以平移缩放视图，或使用鼠标滚轮进行缩放。", "シーンのプレビュー。ドラッグしてズーム ビューをパンするか、マウス ホイールを使用してズームします。", "장면 미리보기. 드래그하여 확대된 보기를 이동하거나 마우스 휠을 사용하여 확대/축소합니다.", "معاينة المشهد. اسحب لتحريك العرض الذي تم تكبيره/تصغيره، أو استخدم عجلة الماوس للتكبير/التصغير."),
  "The selected asset is not a visual media file, so the editor cannot draw a frame preview.": m("L'élément sélectionné n'est pas un fichier multimédia visuel, l'éditeur ne peut donc pas dessiner d'aperçu d'image.", "El recurso seleccionado no es un archivo multimedia visual, por lo que el editor no puede dibujar una vista previa del fotograma.", "所选资源不是视觉媒体文件，因此编辑器无法绘制帧预览。", "選択したアセットはビジュアル メディア ファイルではないため、エディターはフレーム プレビューを描画できません。", "선택한 자산은 시각적 미디어 파일이 아니므로 편집기에서 프레임 미리보기를 그릴 수 없습니다.", "الأصل المحدد ليس ملف وسائط مرئي، لذا لا يمكن للمحرر رسم معاينة الإطار."),
  "Unknown location": m("Lieu inconnu", "Ubicación desconocida", "地点未知", "不明な場所", "알 수 없는 위치", "موقع غير معروف"),
  "Upload or assign background media for this scene.": m("Téléchargez ou attribuez un média d'arrière-plan pour cette scène.", "Cargue o asigne medios de fondo para esta escena.", "为此场景上传或指定背景媒体。", "このシーンのバックグラウンド メディアをアップロードまたは割り当てます。", "이 장면에 대한 배경 미디어를 업로드하거나 할당합니다.", "قم بتحميل أو تعيين وسائط الخلفية لهذا المشهد."),
  "Upload or assign background media in the Scenes tab to preview it here.": m("Téléchargez ou attribuez un média d'arrière-plan dans l'onglet Scènes pour en prévisualiser ici.", "Cargue o asigne medios de fondo en la pestaña Escenas para obtener una vista previa aquí.", "在“场景”选项卡中上传或分配背景媒体以在此处预览。", "[シーン] タブでバックグラウンド メディアをアップロードまたは割り当てて、ここでプレビューします。", "여기에서 미리 보려면 장면 탭에서 배경 미디어를 업로드하거나 할당하세요.", "قم بتحميل أو تعيين وسائط الخلفية في علامة التبويب \"المشاهد\" لمعاينتها هنا."),
  "{label}: {name}": m("{label} : {name}", "{label}: {name}", "{label}: {name}", "{label}: {name}", "{label}: {name}", "{label}: {name}"),
  "{name}: interactive region over the scene. Click to activate this hotspot.": m("{name} : région interactive sur la scène. Cliquez pour activer ce hotspot.", "{name}: región interactiva sobre la escena. Haga clic para activar este punto de acceso.", "{name}：场景上方的交互区域。单击以激活该热点。", "{name}: シーン上のインタラクティブ領域。クリックしてこのホットスポットをアクティブにします。", "{name}: 장면의 대화형 영역입니다. 이 핫스팟을 활성화하려면 클릭하세요.", "{name}: منطقة تفاعلية فوق المشهد. انقر لتفعيل نقطة الاتصال هذه."),
  "{name}: interactive region over the scene. Click to select and edit this hotspot.": m("{name} : région interactive sur la scène. Cliquez pour sélectionner et modifier ce point d'accès.", "{name}: región interactiva sobre la escena. Haga clic para seleccionar y editar este punto de acceso.", "{name}：场景上方的交互区域。单击以选择并编辑该热点。", "{name}: シーン上のインタラクティブ領域。クリックしてこのホットスポットを選択し、編集します。", "{name}: 장면의 대화형 영역입니다. 이 핫스팟을 선택하고 편집하려면 클릭하세요.", "{name}: منطقة تفاعلية فوق المشهد. انقر لتحديد وتحرير نقطة الاتصال هذه."),
}, { allowSourceEqual: ["MAGE2", "{label}: {name}"] });
